# Generated by Django 3.2.4 on 2021-07-19 13:45
import django.contrib.auth.models
from django.db import migrations


def create_groups(apps, _):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Group = apps.get_model('auth', 'Group')
    providers_group, _ = Group.objects.get_or_create(name='Provider')
    buyers_group, _ = Group.objects.get_or_create(name='Buyer')

    PyPlayyUser = apps.get_model('accounts', 'PyPlayyUser')
    for user in PyPlayyUser.objects.all():
        user.groups.add(buyers_group)


def remove_groups(apps, _):
    PyPlayyUser = apps.get_model('accounts', 'PyPlayyUser')
    for user in PyPlayyUser.objects.all():
        user.groups.clear()

    Group = apps.get_model('auth', 'Group')
    providers_group, _ = Group.objects.filter(name='Provider').delete()
    buyers_group, _ = Group.objects.filter(name='Buyer').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length')
    ]

    operations = [
        migrations.RunPython(create_groups, remove_groups)
    ]
