# Generated by Django 3.2.4 on 2021-07-19 13:45
import django.contrib.auth.models
from django.db import migrations


def create_groups(apps, _):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Group = apps.get_model('auth', 'Group')
    sellers_group, _ = Group.objects.get_or_create(name='Seller')
    buyers_group, _ = Group.objects.get_or_create(name='Buyer')

    PyPlayyUser = apps.get_model('accounts', 'PyPlayyUser')
    for user in PyPlayyUser.objects.all():
        user.groups.add(buyers_group)


def remove_groups(apps, _):
    Group = apps.get_model('auth', 'Group')
    sellers_group = Group.objects.get(name='Seller')
    buyers_group = Group.objects.get(name='Buyer')

    PyPlayyUser = apps.get_model('accounts', 'PyPlayyUser')
    for user in PyPlayyUser.objects.all():
        user.groups.remove(sellers_group, buyers_group)

    sellers_group.delete()
    buyers_group.delete()


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length')
    ]

    operations = [
        migrations.RunPython(create_groups, remove_groups)
    ]
