# Generated by Django 3.2.4 on 2021-07-22 07:50

import django.db.models.deletion
from django.db import migrations, models


def migrate_old_products(apps, _):
    Auction = apps.get_model('auctions', 'Auction')
    NewProduct = apps.get_model('products', 'Product')

    for auction in Auction.objects.all():
        old_product = auction.product_id
        new_product, _ = NewProduct.objects.get_or_create(title=old_product.title, description=old_product.description,
                                                          category=old_product.category, pub_date=old_product.pub_date)
        auction.new_product_id = new_product
        auction.save()


def rollback_new_products(apps, _):
    Auction = apps.get_model('auctions', 'Auction')
    OldProduct = apps.get_model('auctions', 'Product')

    for auction in Auction.objects.all():
        new_product = auction.new_product_id
        old_product, _ = OldProduct.objects.get_or_create(title=new_product.title, description=new_product.description,
                                                          category=new_product.category, pub_date=new_product.pub_date)
        auction.product_id = old_product
        auction.save()


class Migration(migrations.Migration):
    dependencies = [
        ('products', '0001_initial'),
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.product'),
        ),
        migrations.AddField(
            model_name='auction',
            name='new_product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.RunPython(migrate_old_products, rollback_new_products),
        migrations.RemoveField(
            model_name='auction',
            name='product_id',
        ),
        migrations.RenameField(
            model_name='auction',
            old_name='new_product_id',
            new_name='product_id',
        ),
        migrations.AlterField(
            model_name='auction',
            name='product_id',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
