# Generated by Django 3.2.4 on 2021-07-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_migrate_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
