# Generated by Django 3.2.4 on 2021-07-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('FRU', 'Fruits'), ('VEG', 'Vegetables')], max_length=3)),
                ('pub_date', models.DateTimeField(verbose_name='date_published')),
            ],
        ),
    ]
