# Generated by Django 3.2.4 on 2021-07-23 12:18

import django.db.models.deletion
from django.db import migrations, models


def migrate_old_product_groups(apps, _):
    Product = apps.get_model('products', 'Product')
    NewProductGroup = apps.get_model('product_groups', 'ProductGroup')

    for product in Product.objects.all():
        old_product_group = product.product_group_id
        new_product_group, _ = NewProductGroup.objects.get_or_create(name=old_product_group.name)
        product.new_product_group_id = new_product_group
        product.save()


def rollback_new_product_groups(apps, _):
    Product = apps.get_model('products', 'Product')
    OldProductGroup = apps.get_model('products', 'ProductGroup')

    for product in Product.objects.all():
        new_product_group = product.new_product_group_id
        old_product_group, _ = OldProductGroup.objects.get_or_create(name=new_product_group.name)
        product.product_group_id = old_product_group
        product.save()


class Migration(migrations.Migration):
    dependencies = [
        ('product_groups', '0001_initial'),
        ('products', '0002_product_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productgroup'),
        ),
        migrations.AddField(
            model_name='product',
            name='new_product_group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='product_groups.productgroup'),
        ),
        migrations.RunPython(migrate_old_product_groups, rollback_new_product_groups),
        migrations.RemoveField(
            model_name='product',
            name='product_group_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='new_product_group_id',
            new_name='product_group_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_group_id',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE,
                                    to='product_groups.productgroup'),
        ),
    ]
